# Generated by Django 5.0.4 on 2024-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_countrieslist_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrieslist',
            name='image',
            field=models.ImageField(default='null_flag', upload_to='images'),
        ),
    ]
