# Generated by Django 5.0.4 on 2024-05-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_countrieslist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrieslist',
            name='description',
        ),
    ]
