# Generated by Django 5.0.4 on 2024-05-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_countrieslist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrieslist',
            name='description',
            field=models.TextField(default='no_description', verbose_name='Описание страны'),
        ),
    ]
