# Generated by Django 5.0.4 on 2024-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quizsessioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrieslist',
            name='id',
            field=models.CharField(default='null_id', max_length=50, primary_key=True, serialize=False, verbose_name='Id страны'),
        ),
    ]
