# Generated by Django 5.0.4 on 2024-05-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_countrieslist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsessioninfo',
            name='round_counter',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер раунда'),
        ),
    ]
