# Generated by Django 5.0.4 on 2024-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quizsessioninfo_round_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsessioninfo',
            name='call_from_question_page',
            field=models.CharField(default=False, max_length=50, verbose_name='Проверка перехода со страницы с вопросом'),
        ),
    ]
